module.exports = app => {
    require("./auth")(app)
    require("./admin")(app)
    require("./adminCMS")(app)
    require("./config")(app)
    require("./banner")(app)
    require("./category")(app)
    require("./product")(app)
    require('./solution')(app)
    require('./customerExperience')(app)
    require('./power')(app)
    require('./client')(app)
    require('./history')(app)
    require('./boardDirector')(app)
}