-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgznzggKKiGAJDdyLm
acXcCEi24AciUYYgf1n+X5gxr++gCgYIKoZIzj0DAQehRANCAAT3CNcguILjyqoJ
O1ZxhfdfMDA7udlBNQ2Vo+IdbRVsDQ/f8y+aEAxTXko3ILbPDeOCwLQiVVv++CRn
Wuvt/0bd
-----END PRIVATE KEY-----